# -*- coding: utf-8 -*-
"""물류 유통량 예측 경진대회.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpEEMdYHA2cLBnILg3FLZVgdv_kzPJQH

## 데이터 불러오기
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/train.csv')
test = pd.read_csv('/content/drive/MyDrive/test.csv')

submission = pd.read_csv('/content/drive/MyDrive/sample_submission.csv')

train.head()

test.head()

train.info()

test.info()

train.isnull().sum()

"""## 데이터 전처리"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(train['물품_카테고리'])

train['물품_카테고리'] = encoder.transform(train['물품_카테고리'])
test['물품_카테고리'] = encoder.transform(test['물품_카테고리'])

"""## 모델링"""

from lightgbm import LGBMRegressor

train_X = train.drop('운송장_건수',axis = 1)
train_Y = train['운송장_건수']

#모델 정의
model = LGBMRegressor()

# 모델 학습
model.fit(train_X,train_Y)

# test 데이터 예측
pred = model.predict(test)

"""## 정답파일 생성"""

submission.to_csv('/content/drive/MyDrive/baseline.csv',index = False)